### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/sockethub#1]
* [ ] add a full example
* [ ] add new generic "set socket key/value"
* [ ] add new generic "set global key/value"

**Comment by moul** [comment]
* [ ] add a full example
* [ ] add new generic "set socket key/value"
* [ ] add new generic "set global key/value"
